services:
  finrl-meta:
    image: finrl-meta:latest
    working_dir: /workspace
    build:
      context: ../
      dockerfile: ./docker/Dockerfile

    depends_on:
      - mlflow
    
    command: ["/bin/bash"]
    tty: true
    env_file:
      - ../.devcontainer/.env
  
    # setting repo root folder as container workspace
    volumes:
      - .././:/workspace
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0

    command: ["mlflow", "server", "-h", "0.0.0.0", "-p", "5000"]

    # exposing the port that will be used by MLFlow
    ports:
      - "5000:5000"

